### ISSUE TITLE
gc-merge-devnet-0 deadlock Jun 26

### ISSUE THREAD

**Issue by dapplion** [gnosischain/consensus-deployment-ansible#6]
------

Nethermind ([user list](https://github.com/gnosischain/consensus-deployment-ansible/blob/6d9bbf6dde9abb6501abdd2fa3c6d4eb75dc7394/gc-merge-devnet-0/inventory/group_vars/eth1client_nethermind.yml#L8)) and Lighthouse ([user list](https://github.com/gnosischain/consensus-deployment-ansible/blob/6d9bbf6dde9abb6501abdd2fa3c6d4eb75dc7394/gc-merge-devnet-0/inventory/group_vars/eth2client_lighthouse.yml#L10)) devs can ssh to hosts ([ip list here](https://github.com/gnosischain/consensus-deployment-ansible/blob/master/gc-merge-devnet-0/inventory/inventory.ini)) `ssh devops@<ip>`. Same as Pari's deployments

------

- gc-merge-devnet-0 was launched at Jun 25 2022 09:05:00 GMT+0000 https://github.com/gnosischain/consensus-deployment-ansible/pull/2. 8 validating clients, all lighthouse-nethermind, each has 100 keys, network of 800 validators total. The first two nodes are POSDAO validators.
  - Beaconchain explorer http://164.92.181.194:3333/
  - Blockscout explorer http://164.92.181.194:3334/
- TTD was reached at Jun 25 2022 10:22:10 GMT+0000 as expected and merge block finalized
- At 22:51:00 GMT+0000 the chain started to fail to produce blocks
- A few more blocks were produced in the next 30 minutes until the chain stalled indefinitely.

Some relevant metrics
![Screenshot from 2022-06-27 14-21-54](https://user-images.githubusercontent.com/35266934/176159179-b3f6aa5d-2538-49fc-abba-b8bd79c17e33.png)
![Screenshot from 2022-06-27 14-23-46](https://user-images.githubusercontent.com/35266934/176159207-ae0428a9-48f5-467e-a522-b2deb491bb13.png)
![Screenshot from 2022-06-27 14-25-36](https://user-images.githubusercontent.com/35266934/176159228-0596e8a3-0033-4033-9069-698ed881ce93.png)
![Screenshot from 2022-06-27 14-40-28](https://user-images.githubusercontent.com/35266934/176159249-d56d2a31-a57d-4d6b-966a-9281d74f4f2b.png)

Digging lighthouse logs of merge-devnet-0-lighthouse-nethermind-3 I found

```
Jun 26 22:51:13.349 DEBG Execution engine call failed            id: http://127.0.0.1:8560/, error: ServerMessage { code: -38002, message: "Inconsistent forkchoiceState - safe block hash. Request: ForkchoiceState: (HeadBlockHash: 0xa2e14ea188d4dc9b247b45367a4b45b45eabfe5ebbf0cd15eaba5ccc4902ff7b, SafeBlockHash: 0xa2e14ea188d4dc9b247b45367a4b45b45eabfe5ebbf0cd15eaba5ccc4902ff7b, FinalizedBlockHash: 0x528f0716d2431e2cf59c93ef2f9af7350dd409de4b40fdae617bef4b15f7d02d) PayloadAttributes: (Timestamp: 1656283875, PrevRandao: 0xb5aec702d8c74b392586b2c39acc51b5ebe0313e951429bd65f5fc1b1a1dda2a, SuggestedFeeRecipient: 0xf97e180c050e5ab072211ad2c213eb5aee4df134)" }, service: exec

Jun 26 22:51:13.353 WARN Error whilst processing payload status  error: Api { id: "http://127.0.0.1:8560/", error: ServerMessage { code: -38002, message: "Inconsistent forkchoiceState - safe block hash. Request: ForkchoiceState: (HeadBlockHash: 0xa2e14ea188d4dc9b247b45367a4b45b45eabfe5ebbf0cd15eaba5ccc4902ff7b, SafeBlockHash: 0xa2e14ea188d4dc9b247b45367a4b45b45eabfe5ebbf0cd15eaba5ccc4902ff7b, FinalizedBlockHash: 0x528f0716d2431e2cf59c93ef2f9af7350dd409de4b40fdae617bef4b15f7d02d) PayloadAttributes: (Timestamp: 1656283875, PrevRandao: 0xb5aec702d8c74b392586b2c39acc51b5ebe0313e951429bd65f5fc1b1a1dda2a, SuggestedFeeRecipient: 0xf97e180c050e5ab072211ad2c213eb5aee4df134)" } }, service: exec
```

Seems that Nethermind rejects forkchoice updates due to `Inconsistent forkchoiceState - safe block hash`.
- Potentially related https://github.com/sigp/lighthouse/issues/3189

**Comment by michaelsproul** [comment]
Posting other findings here as I come across them.

## Finding 1: re-orgs

Some nodes saw long re-orgs around the time the network died:

On  `merge-devnet-0-lighthouse-nethermind-3`:

> Jun 26 22:54:08.313 WARN Beacon chain re-org, reorg_distance: 41, new_slot: 27189, new_head: 0xb2b89b185669504c9d4f4ce5b8ed7f50718015c1c4a1133d40702a4892d5c30c, new_head_parent: 0xd0390c954015187b3cb46ee860438157721b3a6ab5ec40987bd6613ac5d577f7, previous_slot: 27225, previous_head: 0x08dd5f7e8203848af8d157f0ff7b9e7a5324723cfd0adb6a36b92a21cee9ee24, service: beacon, module: beacon_chain::beacon_chain:3562

On `merge-devnet-0-lighthouse-nethermind-6`:

> Jun 26 22:52:52.099 WARN Beacon chain re-org, reorg_distance: 24, new_slot: 27189, new_head: 0xb2b89b185669504c9d4f4ce5b8ed7f50718015c1c4a1133d40702a4892d5c30c, new_head_parent: 0xd0390c954015187b3cb46ee860438157721b3a6ab5ec40987bd6613ac5d577f7, previous_slot: 27208, previous_head: 0x2c610e76f830feab1bb928f4a227c6117e0f62facf5c39f314172cf8564fb1f8, service: beacon, module: beacon_chain::beacon_chain:3562

> Jun 26 23:19:26.057 WARN Beacon chain re-org, reorg_distance: 78, new_slot: 27437, new_head: 0xc1acd308ea5be5ef10853718006e4cef686692d10bdece545ca0487f0e39a823, new_head_parent: 0xb0a45e8d183c592b554d8618339162475ecc8356e886e676da21529743a48e17, previous_slot: 27494, previous_head: 0x9132e9bf67aa64e2ddb37615743a1d366c99c872fbc6882310b9df911a78d923, service: beacon, module: beacon_chain::beacon_chain:3562

List of nodes that didn't re-org:

- `merge-devnet-0-lighthouse-nethermind-1`
- `merge-devnet-0-lighthouse-nethermind-2`
- `merge-devnet-0-lighthouse-nethermind-4`
- `merge-devnet-0-lighthouse-nethermind-5`
- `merge-devnet-0-lighthouse-nethermind-7`
- `merge-devnet-0-lighthouse-nethermind-8`

## Cause?

Node 3's EE starting going offline 6 minutes before the re-org:

> Jun 26 22:48:36.350 WARN Error whilst processing payload status, error: Offline { id: "http://127.0.0.1:8560/" }, service: exec, module: execution_layer::payload_status:177

It starts struggling to import blocks

> Jun 26 22:48:40.443 DEBG Invalid gossip beacon block, block slot: 27164, block root: 0x18a314c62fe4577836ebfba6d88a2e427ef5c1e18a7bda99d6df497c54374068, outcome: Err(ExecutionPayloadError(RequestFailed(EngineErrors([Offline { id: "http://127.0.0.1:8560/" }])))), module: network::beacon_processor::worker::gossip_methods:947

It eventually manages to import 27164 but then gets stuck on it until 22:52:

> Jun 26 22:48:49.371 DEBG Delayed head block, set_as_head_delay: Some(54.248326ms), imported_delay: Some(5.097045279s), observed_delay: Some(4.21967422s), block_delay: 9.370967825s, slot: 27164, proposer_index: 160, block_root: 0x18a314c62fe4577836ebfba6d88a2e427ef5c1e18a7bda99d6df497c54374068, service: beacon, module: beacon_chain::beacon_chain:3698
...
> Jun 26 22:48:50.077 DEBG Block is from a past failed chain. Dropping, block_slot: 27166, block_root: 0x7fb0f1b9b73557b664905ed08b6f8cf510e7be697e71469c6e8c7711977c8dfd, service: sync, module: network::sync::block_lookups:116
...
> Jun 26 22:52:37.502 DEBG Slot timer, sync_state: Syncing Head Chain, current_slot: 27211, head_slot: 27164, head_block: 0x18a3…4068, finalized_epoch: 1695, finalized_root: 0x5d42…7d8a, peers: 9, service: slot_notifier, module: client::notifier:176

Shortly after this the EE comes back online fully and the re-org occurs. Node 3 produces two of its own local blocks atop a stale 40-slot-old head before the re-org:

> Jun 26 22:53:35.986 DEBG Cloned snapshot for late block/skipped slot, block_delay: None, parent_root: 0x44fbd32169d1ce081e05457d48dd42d5da6f2796d355568f8f5f7dc89d4eae9a, parent_slot: 27183, slot: 27223, service: beacon, module: beacon_chain::block_verification:1555
> Jun 26 22:53:37.624 INFO Valid block from HTTP API, slot: 27223, proposer_index: 243, root: 0x0a61…5944, block_delay: 971.484347ms, module: http_api:961
> Jun 26 22:53:46.658 INFO Valid block from HTTP API, slot: 27225, proposer_index: 289, root: 0x08dd…ee24, block_delay: 1.565611275s, module: http_api:961

## Finding 2: death by finalization

Despite the absence of nodes 3 and 6, the rest of the nodes manage to finalize without them, finalizing the troublesome block hash `0xa2e14ea188d4dc9b247b45367a4b45b45eabfe5ebbf0cd15eaba5ccc4902ff7b`:

> Jun 26 22:56:10.101 INFO Issuing forkchoiceUpdated, id: http://127.0.0.1:8560/, forkchoice_state: ForkChoiceState { head_block_hash: ExecutionBlockHash(0x334acee97bb43a3fb2502646f47c7e7572cf412785895350e8d27a3ea6cd568d), safe_block_hash: ExecutionBlockHash(0x334acee97bb43a3fb2502646f47c7e7572cf412785895350e8d27a3ea6cd568d), finalized_block_hash: ExecutionBlockHash(0xa2e14ea188d4dc9b247b45367a4b45b45eabfe5ebbf0cd15eaba5ccc4902ff7b) }, service: exec, module: execution_layer::engines:202

Milliseconds later, payload reconstruction fails:

> Jun 26 22:56:10.109 ERRO Error fetching block for peer, error: ExecutionLayerErrorPayloadReconstruction(ExecutionBlockHash(0xa2e14ea188d4dc9b247b45367a4b45b45eabfe5ebbf0cd15eaba5ccc4902ff7b), EngineErrors([Api { id: "http://127.0.0.1:8560/", error: Json(Error("missing field `baseFeePerGas`", line: 0, column: 0)) }, Api { id: "http://127.0.0.1:8560/", error: Json(Error("missing field `baseFeePerGas`", line: 0, column: 0)) }])), block_root: 0xb2b89b185669504c9d4f4ce5b8ed7f50718015c1c4a1133d40702a4892d5c30c, module: network::beacon_processor::worker::rpc_methods:295

(logs from node 1)

This is the process by which Lighthouse re-assembles a full `BeaconBlock` from the block in its database (without payload) and the payload reconstructed from the EE using `eth_getBlockByHash`. A failure here means two things in our context:

1. That block is now basically unavailable on the p2p network. All the Lighthouse-Nethermind nodes will hit this issue and be unable to serve the block. This feature was designed with heterogeneous networks in mind, so we're suffering from the lack of client diversity here. TODO: check if Prysm and Lodestar tried to serve this block.
2. These repeated failures cause the otherwise healthy finalizing nodes (all but 3 and 6) to mark their execution engines as offline, which prevents them from producing more blocks.

Outcome: the network is dead.

## Summary of issues

* Lighthouse's handling of offline execution engines needs more work and more testing. We should try to avoid failing block import and getting stuck due to transient EE connectivity issues. Related: https://github.com/sigp/lighthouse/issues/3032, https://github.com/sigp/lighthouse/pull/3269.
* We need to fix the incompatibility between Nethermind and Lighthouse that is causing the payload reconstruction issues. I've dumped the execution block that started the trouble [here](https://gist.github.com/michaelsproul/a1caf547ff1c2bf4cf9e74f75587c3bf), and indeed it lacks the `baseFeePerGas` field. Is it possible that the devnet was configured without EIP-1559 enabled? I'll leave this to @dapplion to investigate.

**Comment by michaelsproul** [comment]
Also related: https://github.com/sigp/lighthouse/issues/3176

**Comment by dapplion** [comment]
Closing stale issue
